name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # 🔥 Upload FULL dist folder (important fix)
      - name: Upload dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.14.103.172
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist"
          target: "/home/ubuntu"

      # 🔥 Clean + copy properly + fix permissions
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.14.103.172
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/admin/*
            sudo cp -r /home/ubuntu/dist/* /var/www/admin/
            sudo chown -R www-data:www-data /var/www/admin
            sudo systemctl restart nginx